  - type: passiveScan-config           # Passive scan configuration
    parameters:
      maxAlertsPerRule:                # Int: Maximum number of alerts to raise per rule, default: 0 unlimited
	  scanOnlyInScope:                 # Bool: Only scan URLs in scope (recommended), default: true
      maxBodySizeInBytesToScan:        # Int: Maximum body size to scan, default: 0 - will scan all messages
