  - type: passiveScan-config           # Passive scan configuration
    parameters:
      maxAlertsPerRule:                # Int: Maximum number of alerts to raise per rule, default: 0 unlimited
      scanOnlyInScope:                 # Bool: Only scan URLs in scope (recommended), default: true
      maxBodySizeInBytesToScan:        # Int: Maximum body size to scan, default: 0 - will scan all messages
      enableTags:                      # Bool: Enable passive scan tags, default: false - enabling them can impact performance
      disableAllRules:                 # Bool: If true then will disable all rules before applying the settings in the rules section, default: false
    rules:                             # A list of one or more passive scan rules and associated settings which override the defaults
    - id:                              # Int: The rule id as per https://www.zaproxy.org/docs/alerts/
      name:                            # String: The name of the rule for documentation purposes - this is not required or actually used
      threshold:                       # String: The Alert Threshold for this rule, one of Off, Low, Medium, High, default: Medium