name: CI Remote

on:
  workflow_dispatch:
  schedule:
    # Once a month
    - cron:  '0 8 18 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            wdm
      - run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4g --continue --no-parallel test
        env:
          ZAP_REMOTE_TESTS: 1
